## in this class we gona study the numpy
* first we starts installation using the pip
* pip install nptyping 
* along with beartype


In [2]:
!pip install nptyping beartype

  Using cached nptyping-2.5.0-py3-none-any.whl (37 kB)
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------------------------- ------------ 41.0/61.2 kB 653.6 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 547.9 kB/s eta 0:00:00
   ---------------------------------------- 0.0/819.1 kB ? eta -:--:--
   - ------------------------------------- 41.0/819.1 kB 991.0 kB/s eta 0:00:01
   --- ----------------------------------- 71.7/819.1 kB 991.0 kB/s eta 0:00:01
   ----- -------------------------------- 112.6/819.1 kB 726.2 kB/s eta 0:00:01
   ----- -------------------------------- 122.9/819.1 kB 722.1 kB/s eta 0:00:01
   -------- ----------------------------- 174.1/819.1 kB 748.1 kB/s eta 0:00:01
   -------- ----------------------------- 174.1/819.1 kB 748.1 kB/s eta 0:00:01
   --------- ---------------------------- 194.6/819.1 kB 590.8 kB/s eta 0:00:02
   ---------- --------------------------- 225.3/819.1 kB 573.4 kB/s eta 0:00:02
  

In [4]:
!pip install numpy



## sclar value object

In [2]:
import numpy as np

a : np.ndarray = np.array(1000)

display(a) # Display the array
display(a.shape) # Display the shape of the array
display(a.ndim) # Display the number of dimensions of the array
display(a.size) # Display the number of elements in the array
display(a.dtype) # Display the data type of the array
display(a.itemsize) # Display the size of each element in the array
display(type(a))


array(1000)

()

0

1

dtype('int32')

4

numpy.ndarray

## Vector type object

In [3]:
import numpy as np

a : np.ndarray = np.array([1,2,3,4,5,6,7,8,9,10]) 

display(a) # Display the array
display(a.shape) # Display the shape of the array
display(a.ndim) # Display the number of dimensions of the array
display(a.size) # Display the number of elements in the array
display(a.dtype) # Display the data type of the array
display(a.itemsize) # Display the size of each element in the array
display(type(a))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

(10,)

1

10

dtype('int32')

4

numpy.ndarray

In [2]:
# matrix data having 2 dimession

import numpy as np

a :np.ndarray=np.array([[1,2,3],[4,5,6],[7,8,9]])



display(a) # Display the array
display(a.shape) # Display the shape of the array
display(a.ndim) # Display the number of dimensions of the array
display(a.size) # Display the number of elements in the array
display(a.dtype) # Display the data type of the array
display(a.itemsize) # Display the size of each element in the array
display(type(a))
display(a[1][2])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

(3, 3)

2

9

dtype('int32')

4

numpy.ndarray

6

In [7]:
#Now according to the new typing patren with NDarray spourt

from typing import Any
from nptyping import NDArray, UInt16, UInt64 ,Shape 

data : NDArray[Shape["10"],Any]= np.arange(1,10)
display(data)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:

from typing import Any
from nptyping import NDArray, UInt16, UInt64 ,Shape 

ndata : NDArray[Shape["20"],Any]= np.arange(1,20)
display(ndata)
ndata[5:10] = 1000
print(ndata)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

[   1    2    3    4    5 1000 1000 1000 1000 1000   11   12   13   14
   15   16   17   18   19]


In [12]:
#selectin with boolean
import numpy as np
from nptyping import NDArray,Shape,Bool 
#this is an our atuaal from which we select
select :NDArray[Shape["20"],Any]= np.array([1,2,3,4])
boolData : NDArray[Shape["10"] , Bool] = np.array([True,False,True,False])
#now passing the bool to select
trueResult=select[boolData]
print(f"thes are the true owns{trueResult}")

# now more maupulatin f the narray
modulas = select[select % 2 == 0]
print(f"these are the values where 2 modulas is zero{modulas}")

thes are the true owns[1 3]
these are the values where 2 modulas is zero[2 4]


In [18]:
#important functions in np to remaember
#finding the required desire number in the long array
bankData : NDArray[Shape["1"], Any] = np.random.randint(1,100 ,20)
# now we gona find  the desire number is present in data

findings= np.in1d(select , bankData )
# in onedementional data (to find in , this data) will gieve bool
print(f"we find in the large random data array{findings}")

we find in the large random data array[False  True  True False]


In [20]:
display(bankData)
display(select)
print(f" finding intersected data{np.intersect1d(select ,bankData )}")


array([11, 45, 17, 15, 80, 67, 69, 85, 58, 47, 81, 54, 29,  3,  5,  8, 15,
       83,  2, 68])

array([1, 2, 3, 4])

 finding intersected data[2 3]


In [22]:
#where use as findng between 2 array 
x:NDArray[Shape["10"], Any] = np.array([1,2,3,7,8])
y : NDArray[Shape["10"],Any] = np.array([1,6,8,9,4])
display(x)
display(y)
# NOw we gona compair the both array using the array
compair = np.where(x>y , x,y)
display(compair)


            

array([1, 2, 3, 7, 8])

array([1, 6, 8, 9, 4])

array([1, 6, 8, 9, 8])

## Create np array

In [34]:
#2d array
a : NDArray[Shape["*,*"] , Any] = np.array([[1,2,3,3],
                                                     [12,3,4,5]])
display(a)

b : NDArray[Shape["*,*"] , Any] = np.array([[1,2],
                                                     [12,4]])
display(b)
c : NDArray[Shape["*,*"] , Any] = np.array([["s " ,"q"],
                                                     [12,4]])
display(c)


array([[ 1,  2,  3,  3],
       [12,  3,  4,  5]])

array([[ 1,  2],
       [12,  4]])

array([['s ', 'q'],
       ['12', '4']], dtype='<U11')

 ##  creating multidimention arary

In [39]:
d : NDArray[Shape["Size"], Any] = np.arange(1,3)
display(d)
e : NDArray[Shape["Size"], Any] = np.arange(1,9)
display(e)
#Now 2 d array

f : NDArray[Shape["Size,Size"], Any]= np.arange(3*3).reshape(3,3)
display(f)
g : NDArray[Shape["Size,Size"], Any]= np.arange(5*3).reshape(5,3)
display(g)


array([1, 2])

array([1, 2, 3, 4, 5, 6, 7, 8])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [42]:
#making larger arrays
h : NDArray[Shape["Size,Size ,Size"], Any]= np.arange(5*1*3).reshape(5,1,3)
display(h)
#5 is the nnober of total matriz or set of array
#1 is rows
#3 is number of colomns


array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]],

       [[12, 13, 14]]])

In [43]:
h : NDArray[Shape["Size,Size"], Any]= np.arange(5*3*3).reshape(5,3,3)
display(h)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]],

       [[36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [46]:
np.ones((5))


array([1., 1., 1., 1., 1.])

In [47]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [49]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
# now is this we can make the same ones or zeros array with likes
k : NDArray[Shape["Size,Size ,Size"], Any]= np.arange(5*1*3).reshape(5,1,3)
display(k)
np.ones_like((k))

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]],

       [[12, 13, 14]]])

array([[[1, 1, 1]],

       [[1, 1, 1]],

       [[1, 1, 1]],

       [[1, 1, 1]],

       [[1, 1, 1]]])

In [58]:
ndata : NDArray[Shape["10"],Any]= np.arange(1,5)

display(ndata)

print(ndata.min())
print(ndata.max())
print(ndata.mean())
print(ndata.argmin())
print(ndata.argmax()) 
print(ndata.sum())
print(ndata.cumsum())
print(ndata.std())
#or some of the more related array methods

array([1, 2, 3, 4])

1
4
2.5
0
3
10
[ 1  3  6 10]
1.118033988749895


we have to study more content on slising the arrays in simple manners